name: Laravel CI/CD

on:
  push:
    tags:
      - '*'

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - uses: actions/checkout@v2
      - name: List
        run: ls -a && composer -V
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Execute tests
        run: vendor/bin/phpunit
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v2
        with:
          ref: deploy
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          RELEASE_VERSION=${GITHUB_REF#refs/*/}"
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
          cp .env.example .env.local
          sed -i -r "s/^(VUE_APP_VERSION=).*/\1$RELEASE_VERSION/" .env.local
      - run: make update
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add back/*
          git commit --allow-empty -m "Build front-end assets"
          git push -f origin deploy
        working-directory: ./
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: 'cd /var/www/corsnet && sudo bash ./deploy.sh'